# Tensors

In [1]:
import torch
import numpy as np

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

## What is a Tensor ?
- In PyTorch, tensor is data structure used to store and manipulate data
- similar to numpy array but also additional `torch.Tensor` attributes and operations
- benefits over numpy
    - tensor operations can be performed significantly faster using GPU accleration
    - tensor can be stored and manipulated at scale using distributed processing on multiple CPU and GPUs across multiple servers
    - tensors keep track of their graph computations, important in deep learning library

### Simple GPU example

In [3]:
x = torch.tensor(
    [[1,2,3],[4,5,6]], 
    device=device
    )

In [4]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [5]:
y = torch.tensor(
    [[7,8,9],[10,11,12]], 
    device=device)

In [6]:
z = x + y

In [7]:
z

tensor([[ 8, 10, 12],
        [14, 16, 18]])

In [8]:
z.device

device(type='cpu')

also possible to move between CPUs and GPUs
```
x = x.to(device)
y = y.to(device)
z = x + y
z = z.to("cpu")
```

## Creating Tensors

In [9]:
# Create from preexisting arrays
w = torch.tensor([1,2,3])
w = torch.tensor((1,2,3))
w = torch.tensor(np.array([1,2,3]))

In [10]:
# Initalize by size
w = torch.empty(100,200)
w = torch.zeros(100,200)
w = torch.ones(100,200)

In [11]:
# initalized by size with random values
w = torch.rand(100,200)
w = torch.randn(100,200) # normal distribution
w = torch.randint(5,10,(100,200))  # random integers between 5 and 10

In [12]:
# initialized with specified data type or device
w = torch.empty(100,200, dtype=torch.float32, device=device)

## Tensor Attributes

In [13]:
w.dtype

torch.float32

In [14]:
w.ndim

2

In [15]:
w.requires_grad

False

In [16]:
x.layout

torch.strided

## Tensor Operations

### Indexing, Slicing

In [18]:
x = torch.tensor([[1,2],[3,4],[5,6],[7,8]])

In [19]:
x.shape

torch.Size([4, 2])

In [23]:
# Row 1, column 0 (starts from 0)
x[1,0]

tensor(3)

In [22]:
x[1,1]

tensor(4)

In [24]:
x[1,1].item()  # get as a standard Python number

4

In [25]:
x.t()

tensor([[1, 3, 5, 7],
        [2, 4, 6, 8]])

In [26]:
x.view(2,4)  # reshape to 2 rows, 4 columns

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [27]:
y = torch.stack((x,x))
y

tensor([[[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]])

In [28]:
y.shape

torch.Size([2, 4, 2])

In [29]:
a,b = x.unbind(dim=1)

In [30]:
a

tensor([1, 3, 5, 7])

In [31]:
b

tensor([2, 4, 6, 8])

### Tensor Operations for Mathematics

### Automatic Differentiation (Autograd)
- `backward()` function uses PyTorch automatic differentiation package `torch.autograd` to differentiate and compute gradients of tensor based on the chain rule

In [33]:
x = torch.tensor(
    [[1,2,3],[4,5,6]],
    dtype=torch.float,
    requires_grad=True
    )

In [34]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)

$$
f(x) = \sum(x^2)
$$

In [35]:
f = x.pow(2).sum()

In [36]:
f

tensor(91., grad_fn=<SumBackward0>)

$$
\frac{df(x)}{dx} = 2x
$$

In [37]:
f.backward()

In [38]:
x.grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])